### ISSUE TITLE
TMCL.py gio and sio need self parameter

### ISSUE THREAD

**Issue by rbrown-acertaralabs** [ap--/PyStepRocker#1]
PyStepRocker is fantastic...thank you for creating it.
While using it, I noticed that TMCL.py has two bugs inside class TMCLDevice.
The following two method definitions are missing the "self" parameter:

```
def sio(port_number, state):
...
def gio(port_number, bank_number):
```

So the above should read:

```
def sio(self, port_number, state):
...
def gio(self, port_number, bank_number):
```

Thanks!

**Comment by ap--** [comment]
Thanks for the report.
Please send a pull request with your recommended changes for each of the Issues (#1, #2 and #3) so that I can merge them into this repository.

All the best,
-Andreas
